services:
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092   # dùng tên container Kafka
    networks:
      - kafka-net
    restart: unless-stopped

networks:
  kafka-net:
    driver: bridge