services:
  redis:
    image: redis:8.0.2
    container_name: mcp_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:

